services:
  proxy-server:
    build: ./rpc-proxy-server
    ports:
      - 5051:5051
    hostname: proxy-server

  num-service:
    build: ./rpc-num-service
    ports:
      - 5052:5052
    hostname: num-service

  str-service:
    build: ./rpc-str-service
    ports: 
      - 5053:5053
    hostname: str-service

  client:
    build: ./rpc-client
    ports:
      - 5050:5050
    hostname: rpc-client
    stdin_open: true # docker run -i
    tty: true        # docker run -t