services:
  proxy-server:
    build: ./rpc-proxy-server
    ports:
      - 5051:5051
    hostname: proxy-server

  num-service:
    build: ./rpc-num-service
    ports:
      - 52
    hostname: num-service

  str-service:
    build: ./rpc-str-service
    ports:
      - 53
    hostname: str-service

  client:
    build: ./rpc-client
    ports:
      - 5050:5050
    hostname: rpc-client
    tty: true # docker run -t

  redis:
    - image: redis:latest
