services:
  proxy-server:
    build: ./rpc-proxy-server
    ports:
      - 51
    hostname: proxy-server

  num-service:
    build: ./rpc-num-service
    ports:
      - 52
    hostname: num-service

  str-service:
    build: ./rpc-str-service
    ports:
      - 53
    hostname: str-service

  client:
    build: ./rpc-client
    hostname: rpc-client
    stdin_open: true # docker run -i
    tty: true # docker run -t

  redis:
    - image: redis:latest
    - hostname: redis-cache
    - ports:
      - 6379
