services:
  web:
    proxy-server:
      build: ./rpc-proxy-server
      port: 5051

    num-service:
      build: ./rpc-num-service
      port: 5052

    str-service:
      build: ./rpc-str-service
      port: 5053

    client:
      build: ./rpc-client
      port: 5050
      stdin_open: true # docker run -i
      tty: true        # docker run -t
